#!/bin/bash
set -e

# ============================================================
# Bitcoder Agent - Client Install Script
# ============================================================
# Usage: curl -sSL <cloud_url>/api/agent/install.sh | bash -s -- --key=AGENT_KEY
# ============================================================

AGENT_KEY=""
CLOUD_URL=""
INSTALL_DIR="/opt/bitcoder-agent"

for arg in "$@"; do
  case $arg in
    --key=*)
      AGENT_KEY="${arg#*=}"
      ;;
    --cloud=*)
      CLOUD_URL="${arg#*=}"
      ;;
    --dir=*)
      INSTALL_DIR="${arg#*=}"
      ;;
  esac
done

if [ -z "$AGENT_KEY" ]; then
  echo "ERROR: --key is required"
  echo "Usage: curl -sSL <url>/install.sh | bash -s -- --key=bc_ag_xxxxx"
  exit 1
fi

echo "========================================"
echo "  Bitcoder Agent Installer"
echo "========================================"
echo ""

# --- Detect cloud URL from script source ---
if [ -z "$CLOUD_URL" ]; then
  # Try to detect from the download URL
  CLOUD_URL="https://orchestrator.gartanto.site"
fi

echo "[1/7] Checking prerequisites..."

# --- Check OS ---
if [[ "$(uname)" != "Linux" ]]; then
  echo "ERROR: This script only supports Linux."
  exit 1
fi

# --- Install Docker if needed ---
if ! command -v docker &> /dev/null; then
  echo "[2/7] Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl start docker
  systemctl enable docker
  echo "Docker installed."
else
  echo "[2/7] Docker already installed."
fi

# --- Install Docker Compose if needed ---
if ! docker compose version &> /dev/null; then
  echo "       Installing Docker Compose plugin..."
  apt-get update -qq && apt-get install -y -qq docker-compose-plugin 2>/dev/null || {
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m)" \
      -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  }
  echo "Docker Compose installed."
else
  echo "       Docker Compose already available."
fi

# --- Create install directory ---
echo "[3/7] Setting up directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

# --- Download docker-compose.agent.yml ---
echo "[4/7] Downloading docker-compose.agent.yml..."
curl -sSL "${CLOUD_URL}/api/agent/compose" -o "$INSTALL_DIR/docker-compose.yml"

# --- Create .env file ---
echo "[5/7] Creating environment file..."
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p)
POSTGRES_DB="bitcoder"
POSTGRES_USER="bitcoder"

cat > "$INSTALL_DIR/.env" << EOF
# Auto-generated by Bitcoder Agent Installer
AGENT_KEY=${AGENT_KEY}
CLOUD_URL=${CLOUD_URL}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EOF

# --- Pull and start ---
echo "[6/7] Starting services..."
cd "$INSTALL_DIR"
docker compose pull 2>/dev/null || true
docker compose up -d

# --- Wait and verify ---
echo "[7/7] Verifying services..."
sleep 5

echo ""
echo "========================================"
echo "  Installation Complete!"
echo "========================================"
echo ""
echo "  Directory:  $INSTALL_DIR"
echo "  Agent Key:  ${AGENT_KEY:0:12}..."
echo "  Cloud:      $CLOUD_URL"
echo ""
echo "  Agent is connecting to cloud..."
echo "  Check status at: $CLOUD_URL/clients"
echo ""
echo "Useful commands:"
echo "  Logs:        cd $INSTALL_DIR && docker compose logs -f agent"
echo "  Status:      cd $INSTALL_DIR && docker compose ps"
echo "  Restart:     cd $INSTALL_DIR && docker compose restart"
echo "  Stop:        cd $INSTALL_DIR && docker compose down"
echo ""
